import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Sidebare from "@/components/Layout/Sidebare";
import Header from "@/components/Layout/Header";
import MainContext from "@/contexts/MainContext";
import WelcomePopup from "@/components/Layout/WelcomingPopup";


const geistMono = Bricolage_Grotesque({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Système de gestion des ressources humaines",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html
      lang="en"
      className={`${geistMono.className} antialiased`}
    >
      <body className="bg-sidebar ">
        <MainContext  >

          <div className="flex items-start justify-start ">
            <Sidebare />
            <div className=" max-h-screen overflow-auto scrl_none  h-screen flex flex-col items-start justify-start w-full ">
              <Header />
              {children}
              {modal}
              <WelcomePopup />
            </div>
          </div>

        </MainContext>
      </body>

    </html>
  );
}
